# -- String - Defines the role name prefix. Part of the iam role/policy name that will be created
role_name_prefix: "crossplane-eks-"
# -- String - Defines the pod name that will assume the permissions. Part of the iam role/policy name that will be created
pod_name: my-pod-name
# -- String - Defines the cluster name that we are using. Part of the iam role/policy name that will be created
cluster_name: my-cluster-name
# --  Defines if service account and other resources will have the annotation:
# --  "helm.sh/hook: pre-install" and will be create first in any combination with other charts
pre_install_annotations: true
# -- Defines if to create instance profile for the role
createInstanceProfile: false
service_account:
# --  Defines if service account will be created
  create: true
# -- Defines the imagePullSecrets atributes for the service account. (not required)
  # imagePullSecrets:
  # - name: my-secret
# -- # Defines if to enable regional endpoint for the aws sts service (not required)
  sts_regional_endpoints: true
# -- Aws account id for the Iam role trust relationship policy
aws_account_id: "1234567890"
# -- Aws Eks openId connect id for the Iam role trust relationship policy
aws_eks_openId_connect_number: "1111111111222222222GGGGGGGGGPPPPPPPPPP"
# -- Aws region for the Iam role trust relationship policy
aws_region: eu-west-1
# -- map of string -> jsons pairs - Defines the Iam policies that will be created and attached to the Iam role
policies: []
    # policydocument1:
    #     {
    #         "Id": "crossplane-eks-policydocument1",
    #         "Version": "2012-10-17",
    #         "Statement": [
    #             {
    #                 "Action": [
    #                     "iam:CreateServiceLinkedRole"
    #                 ],
    #                 "Condition": {
    #                     "StringEquals": {
    #                         "iam:AWSServiceName": [
    #                             "elasticloadbalancing.amazonaws.com"
    #                         ]
    #                     }
    #                 },
    #                 "Effect": "Allow",
    #                 "Resource": "*",
    #                 "Sid": ""
    #             }
    #         ]
    #     }
    # policydocument2:
    #     {
    #         "Id": "crossplane-eks-policydocument2",
    #         "Version": "2012-10-17",
    #         "Statement": [
    #             {
    #                 "Action": [
    #                     "iam:CreateServiceLinkedRole"
    #                 ],
    #                 "Condition": {
    #                     "StringEquals": {
    #                         "iam:AWSServiceName": [
    #                             "elasticloadbalancing.amazonaws.com"
    #                         ]
    #                     }
    #                 },
    #                 "Effect": "Allow",
    #                 "Resource": "*",
    #                 "Sid": ""
    #             }
    #         ]
    #     }
# -- String - Defines the name of the crossplane provider-config, which should be predefined with Iam full access, for more info, look at aws-provider docs below
provider_config_name: aws-provider
# -- map of string -> string pairs - Iam role and policies Aws tags
tags:
  Component: k8s
  Environment: dev
  ManageBy: crossplane-my-cluster-name
  Name: crossplane-k8s-my-pod
