## pod_name is the name of the pod that is going to assume this new created iam role
## pod_name will be part of the name of the iam/policy that will be created
pod_name: my-pod-name
service_account:
  create: true
  imagePullSecrets: 
   - name: expregistrykey
## cluster_name will be part of the name of the iam/policy that will be created
cluster_name: platform-dev
role_name_prefix: "crossplane-eks-"
aws_account_id: "1234567890"
aws_eks_openId_connect_number: "1111111111222222222GGGGGGGGGPPPPPPPPPP"
aws_region: eu-west-1
policies:
    policydocument1:
        {
            "Id": "crossplane-eks-policydocument1",
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": [
                        "iam:CreateServiceLinkedRole"
                    ],
                    "Condition": {
                        "StringEquals": {
                            "iam:AWSServiceName": [
                                "elasticloadbalancing.amazonaws.com"
                            ]
                        }
                    },
                    "Effect": "Allow",
                    "Resource": "*",
                    "Sid": ""
                }
            ]
        }
    policydocument2:
        {
            "Id": "crossplane-eks-policydocument2",
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": [
                        "iam:CreateServiceLinkedRole"
                    ],
                    "Condition": {
                        "StringEquals": {
                            "iam:AWSServiceName": [
                                "elasticloadbalancing.amazonaws.com"
                            ]
                        }
                    },
                    "Effect": "Allow",
                    "Resource": "*",
                    "Sid": ""
                }
            ]
        }
provider_config_name: aws-provider
tags:
  Component: k8s
  Environment: dev
  ManageBy: crossplane-platform-dev
  Name: crossplane-k8s-aws-load-balancer-controller
  Team: RND
  Type: Platform