
{{  $ms_root := .Values }}

{{ if $ms_root.policies }}
{{ range $policie_entry, $policies_data := $ms_root.policies }}


apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: "{{ $ms_root.pod_name }}-role-policy-attach-{{ $policie_entry }}"
spec:
  forProvider:
    policyArnRef:
      name: "{{ $ms_root.role_name_prefix }}-{{ $ms_root.cluster_name }}-{{ $ms_root.pod_name }}-{{ $policie_entry }}"
    roleNameRef:
      name: "{{ $ms_root.role_name_prefix }}-{{ $ms_root.cluster_name }}-{{ $ms_root.pod_name }}"
  providerConfigRef:
    name: {{ $ms_root.provider_config_name }}


---


{{ end }}
{{ end }}