{{- if or .Values.service_account.create (not (hasKey .Values.service_account "true")) }}
apiVersion: v1
automountServiceAccountToken: true
{{- with .Values.service_account.imagePullSecrets }}
imagePullSecrets:
{{ . | toYaml }}
{{- end }}
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.aws_account_id }}:role/{{ .Values.role_name_prefix }}-{{ .Values.cluster_name }}-{{ .Values.pod_name }}"
  labels:
    {{ .Values.sa_labels | toYaml }}
  name: "{{ .Values.pod_name }}-sa"
{{ end }}