{{ if .Values.createInstanceProfile }}
apiVersion: iam.aws.crossplane.io/v1alpha1
kind: InstanceProfile
metadata:
  name: "{{ .Values.role_name_prefix }}-{{ .Values.cluster_name }}-{{ .Values.pod_name }}"
spec:
  forProvider:
    roleSelector:
      matchLabels:
        addToInstanceProfile: "{{ .Values.role_name_prefix }}-{{ .Values.cluster_name }}-{{ .Values.pod_name }}"  
    tags:
    {{- range $key, $value := .Values.tags }}
      - key: {{ $key }}
        value: {{ $value | quote }}
    {{- end }}
      - key: crossplane-kind
        value: instance-profile.iam.aws.crossplane.io
      - key: crossplane-name
        value: "{{ .Values.role_name_prefix }}-{{ .Values.cluster_name }}-{{ .Values.pod_name }}"
  providerConfigRef:
    name: {{ .Values.provider_config_name }}        
{{ end }}