
{{  $ms_root := .Values }}

{{ if $ms_root.policies }}
{{ range $policie_entry, $policies_data := $ms_root.policies }}


apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: "{{ $ms_root.role_name_prefix }}-{{ $ms_root.cluster_name }}-{{ $ms_root.pod_name }}-{{ $policie_entry }}"
spec:
  deletionPolicy: Delete
  forProvider:
    description:  "{{ $ms_root.role_name_prefix }}-{{ $ms_root.cluster_name }}-{{ $ms_root.pod_name }}-{{ $policie_entry }}"
    document: {{ $policies_data | toJson | quote }}
    name: "{{ $ms_root.role_name_prefix }}-{{ $ms_root.cluster_name }}-{{ $ms_root.pod_name }}-{{ $policie_entry }}"
    tags:
    {{- range $key, $value := $ms_root.tags }}
      - key: {{ $key }}
        value: {{ $value | quote }}
    {{- end }}
      - key: crossplane-kind
          value: policy.iam.aws.crossplane.io
      - key: crossplane-name
        value: "{{ $ms_root.role_name_prefix }}-{{ $ms_root.cluster_name }}-{{ $ms_root.pod_name }}-{{ $policie_entry }}"
  providerConfigRef:
    name: {{ $ms_root.provider_config_name }}



---


{{ end }}
{{ end }}