{{ if .Values.createInstanceProfile }}
apiVersion: iam.aws.crossplane.io/v1alpha1
kind: InstanceProfile
metadata:
  name: {{ include "roleName" . }}
spec:
  forProvider:
    roleSelector:
      matchLabels:
        addToInstanceProfile: {{ include "roleName" . }}
    tags:
    {{- range $key, $value := .Values.tags }}
      - key: {{ $key }}
        value: {{ $value | quote }}
    {{- end }}
      - key: crossplane-kind
        value: instance-profile.iam.aws.crossplane.io
      - key: crossplane-name
        value: {{ include "roleName" . }}
  providerConfigRef:
    name: {{ .Values.provider_config_name }}        
{{ end }}