
{{  $ms_root := .Values }}
{{  $root := . }}
{{ if $ms_root.policies }}
{{ range $policie_entry, $policies_data := deepCopy $ms_root.policies | merge $ms_root.extra_policies }}


apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: "{{ include "roleName" $root }}-{{ $policie_entry }}"
  {{- if $ms_root.pre_install_annotations }}
  annotations:
    helm.sh/hook: pre-install
  {{- end  }}
spec:
  deletionPolicy: Delete
  forProvider:
    description:  "{{ include "roleName" $root }}-{{ $policie_entry }}"
    document: {{ $policies_data | toJson | quote }}
    name: "{{ include "roleName" $root }}-{{ $policie_entry }}"
    tags:
    {{- range $key, $value := $ms_root.tags }}
      - key: {{ $key }}
        value: {{ $value | quote }}
    {{- end }}
      - key: crossplane-kind
        value: policy.iam.aws.crossplane.io
      - key: crossplane-name
        value: "{{ include "roleName" $root }}-{{ $policie_entry }}"
  providerConfigRef:
    name: {{ $ms_root.provider_config_name }}



---


{{ end }}
{{ end }}
