
{{  $ms_root := .Values }}
{{  $root := . }}
{{ if $ms_root.policies }}
{{ range $policie_entry, $policies_data := $ms_root.policies }}


apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: "{{ $ms_root.pod_name }}-attach-{{ $policie_entry }}-{{$root.Release.Name}}"
  {{- if $ms_root.pre_install_annotations }}
  annotations:
    helm.sh/hook: pre-install
  {{- end  }}
spec:
  forProvider:
    policyArnRef:
      name: "{{ include "roleName" $root }}-{{ $policie_entry }}"
    roleNameRef:
      name: "{{ include "roleName" $root }}"
  providerConfigRef:
    name: {{ $ms_root.provider_config_name }}


---


{{ end }}
{{ end }}